[package]
name = "mlp"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
rand = "0.9.0"
ndarray-rand = "0.15.0"

csv = "1.3"
serde = { version = "1.0", features = ["derive"] }  # 用于反序列化